# -*- coding: utf-8 -*-
import os
import io
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image as RLImage, Table, TableStyle, HRFlowable, KeepTogether
from reportlab.lib.enums import TA_CENTER, TA_RIGHT, TA_LEFT
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from PIL import Image
from config import TEMP_DIR, WATERMARK_TEXT
import uuid

# تسجيل الخطوط العربية
_FONTS_REGISTERED = False

def _register_fonts():
    global _FONTS_REGISTERED
    if _FONTS_REGISTERED:
        return
    
    font_paths = [
        "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
        "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
        "/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf",
        "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf"
    ]
    
    for p in font_paths:
        if os.path.exists(p):
            try:
                if "Bold" in p:
                    pdfmetrics.registerFont(TTFont("ArabicBold", p))
                else:
                    pdfmetrics.registerFont(TTFont("ArabicRegular", p))
            except:
                pass
    
    _FONTS_REGISTERED = True


def _arabic(text: str) -> str:
    """تحضير النص العربي"""
    if not text:
        return ""
    try:
        import arabic_reshaper
        from bidi.algorithm import get_display
        if any('\u0600' <= c <= '\u06FF' for c in text):
            return get_display(arabic_reshaper.reshape(text))
    except:
        pass
    return text


def create_pdf_summary(lecture_data: dict, sections: list, output_path: str, dialect: str = "msa") -> str:
    _register_fonts()
    
    is_arabic = dialect not in ("english", "british")
    
    if is_arabic:
        reg_font = "ArabicRegular"
        bold_font = "ArabicBold"
        align = TA_RIGHT
        title_text = _arabic("ملخص المحاضرة")
        sections_text = _arabic("الأقسام التفصيلية")
        keywords_text = _arabic("الكلمات المفتاحية")
        footer_text = _arabic(f"تم إنشاؤه بواسطة {WATERMARK_TEXT}")
    else:
        reg_font = "Helvetica"
        bold_font = "Helvetica-Bold"
        align = TA_LEFT
        title_text = "Lecture Summary"
        sections_text = "Detailed Sections"
        keywords_text = "Keywords"
        footer_text = f"Generated by {WATERMARK_TEXT}"
    
    doc = SimpleDocTemplate(
        output_path,
        pagesize=A4,
        rightMargin=1.5*cm,
        leftMargin=1.5*cm,
        topMargin=2*cm,
        bottomMargin=2*cm
    )
    
    styles = getSampleStyleSheet()
    
    title_style = ParagraphStyle(
        'Title',
        parent=styles['Heading1'],
        fontName=bold_font,
        fontSize=24,
        alignment=TA_CENTER,
        textColor=colors.HexColor("#1a1a2e"),
        spaceAfter=20
    )
    
    heading_style = ParagraphStyle(
        'Heading',
        parent=styles['Heading2'],
        fontName=bold_font,
        fontSize=16,
        alignment=align,
        textColor=colors.HexColor("#16213e"),
        spaceAfter=10,
        spaceBefore=10
    )
    
    body_style = ParagraphStyle(
        'Body',
        parent=styles['Normal'],
        fontName=reg_font,
        fontSize=12,
        alignment=align,
        leading=18,
        spaceAfter=8
    )
    
    keyword_style = ParagraphStyle(
        'Keyword',
        parent=styles['Normal'],
        fontName=bold_font,
        fontSize=11,
        alignment=align,
        textColor=colors.HexColor("#e94560"),
        spaceAfter=5
    )
    
    story = []
    
    # العنوان الرئيسي
    lecture_title = lecture_data.get("title", "المحاضرة التعليمية")
    story.append(Paragraph(_arabic(lecture_title) if is_arabic else lecture_title, title_style))
    story.append(Spacer(1, 0.5*cm))
    
    # نوع المحاضرة
    lecture_type = lecture_data.get("lecture_type", "other")
    type_names = {
        'medicine': '🩺 محاضرة طبية',
        'math': '📐 محاضرة رياضيات',
        'physics': '⚡ محاضرة فيزياء',
        'chemistry': '🧪 محاضرة كيمياء',
        'history': '📜 محاضرة تاريخية',
        'biology': '🧬 محاضرة أحياء',
        'other': '📚 محاضرة تعليمية'
    }
    type_text = type_names.get(lecture_type, '📚 محاضرة تعليمية')
    story.append(Paragraph(_arabic(type_text) if is_arabic else type_text, heading_style))
    story.append(Spacer(1, 0.3*cm))
    
    # الملخص
    summary = lecture_data.get("summary", "")
    if summary:
        story.append(Paragraph(title_text, heading_style))
        story.append(Paragraph(_arabic(summary) if is_arabic else summary, body_style))
        story.append(Spacer(1, 0.5*cm))
    
    # الأقسام
    story.append(Paragraph(sections_text, heading_style))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#e94560")))
    story.append(Spacer(1, 0.3*cm))
    
    temp_images = []
    
    for i, section in enumerate(sections):
        section_title = section.get("title", f"القسم {i+1}")
        section_title = f"{i+1}. {section_title}"
        
        story.append(Paragraph(_arabic(section_title) if is_arabic else section_title, heading_style))
        
        # صورة القسم
        img_bytes = section.get("_image_bytes")
        if img_bytes:
            try:
                pil_img = Image.open(io.BytesIO(img_bytes)).convert("RGB")
                img_path = os.path.join(TEMP_DIR, f"pdf_img_{i}_{uuid.uuid4().hex[:6]}.jpg")
                pil_img.save(img_path, "JPEG", quality=85)
                temp_images.append(img_path)
                
                rl_img = RLImage(img_path, width=12*cm, height=8*cm)
                rl_img.hAlign = 'CENTER'
                story.append(rl_img)
                story.append(Spacer(1, 0.2*cm))
            except:
                pass
        
        # الكلمات المفتاحية
        keywords = section.get("keywords", [])
        if keywords:
            kw_text = " • ".join(keywords[:4])
            story.append(Paragraph(f"{keywords_text}: {_arabic(kw_text) if is_arabic else kw_text}", keyword_style))
        
        story.append(Spacer(1, 0.5*cm))
    
    # تذييل
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#cccccc")))
    story.append(Spacer(1, 0.3*cm))
    story.append(Paragraph(footer_text, body_style))
    
    doc.build(story)
    
    # تنظيف الصور المؤقتة
    for p in temp_images:
        try:
            os.remove(p)
        except:
            pass
    
    return output_path
