import sys
import os
import io
import uuid
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image, Table, TableStyle, HRFlowable, KeepTogether
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT, TA_JUSTIFY
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from PIL import Image as PILImage
from config import TEMP_DIR, WATERMARK_TEXT

_FONTS_REGISTERED = False
_FONT_DIR = os.path.join(os.path.dirname(__file__), "fonts")
_ARABIC_REGULAR = os.path.join(_FONT_DIR, "Amiri-Regular.ttf")
_ARABIC_BOLD = os.path.join(_FONT_DIR, "Amiri-Bold.ttf")
_LATIN_BOLD = "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"
_LATIN_REG = "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"


def _register_fonts():
    global _FONTS_REGISTERED
    if _FONTS_REGISTERED:
        return
    try:
        if os.path.exists(_ARABIC_REGULAR):
            pdfmetrics.registerFont(TTFont("ArabicRegular", _ARABIC_REGULAR))
        if os.path.exists(_ARABIC_BOLD):
            pdfmetrics.registerFont(TTFont("ArabicBold", _ARABIC_BOLD))
        if os.path.exists(_LATIN_BOLD):
            pdfmetrics.registerFont(TTFont("LatinBold", _LATIN_BOLD))
        if os.path.exists(_LATIN_REG):
            pdfmetrics.registerFont(TTFont("LatinReg", _LATIN_REG))
        _FONTS_REGISTERED = True
    except Exception as e:
        print(f"Font registration failed: {e}")


def _ar(text: str) -> str:
    if not text:
        return text
    try:
        import arabic_reshaper
        from bidi.algorithm import get_display
        return get_display(arabic_reshaper.reshape(str(text)))
    except Exception:
        return str(text)


def _clean(text: str) -> str:
    if not text:
        return ""
    result = []
    for ch in str(text):
        cp = ord(ch)
        if (cp < 0x2000 or 0x0600 <= cp <= 0x06FF or
                0xFB50 <= cp <= 0xFDFF or 0xFE70 <= cp <= 0xFEFF or
                0x0020 <= cp <= 0x007E):
            result.append(ch)
        else:
            result.append(" ")
    return "".join(result).strip()


def _ar_font(bold: bool = False) -> str:
    if bold and os.path.exists(_ARABIC_BOLD):
        return "ArabicBold"
    if os.path.exists(_ARABIC_REGULAR):
        return "ArabicRegular"
    return "Helvetica-Bold" if bold else "Helvetica"


def _en_font(bold: bool = False) -> str:
    if bold and os.path.exists(_LATIN_BOLD):
        return "LatinBold"
    if os.path.exists(_LATIN_REG):
        return "LatinReg"
    return "Helvetica-Bold" if bold else "Helvetica"


async def create_pdf_summary(lecture_data: dict, sections: list, output_path: str, dialect: str = "msa") -> str:
    """إنشاء ملف PDF ملخص للمحاضرة"""
    _register_fonts()
    
    is_english = dialect in ("english", "british")
    
    if is_english:
        reg_font = _en_font(bold=False)
        bold_font = _en_font(bold=True)
        def fmt(t): return _clean(t)
        align_body = TA_LEFT
        labels = {
            "summary": "Summary",
            "key_points": "Key Points",
            "sections_head": "Detailed Sections",
            "keywords_lbl": "Keywords:",
            "footer": f"Generated by Zakros Smart Education Bot | {WATERMARK_TEXT}",
        }
        type_labels = {
            "medicine": "Medical Lecture", "science": "Science Lecture",
            "math": "Mathematics", "literature": "Literature",
            "computer": "Computer Science", "history": "History",
            "business": "Business", "other": "Educational Lecture",
        }
        default_title = "Lecture Summary"
    else:
        reg_font = _ar_font(bold=False)
        bold_font = _ar_font(bold=True)
        def fmt(t): return _ar(_clean(t))
        align_body = TA_RIGHT
        labels = {
            "summary": _ar("الملخص"),
            "key_points": _ar("النقاط الرئيسية"),
            "sections_head": _ar("الأقسام التفصيلية"),
            "keywords_lbl": _ar("الكلمات المفتاحية:"),
            "footer": _ar(f"تم إنتاجه بواسطة بوت التعليم الذكي | {WATERMARK_TEXT}"),
        }
        type_labels = {
            "medicine": _ar("محاضرة طبية"), "science": _ar("محاضرة علمية"),
            "math": _ar("رياضيات"), "literature": _ar("أدب ولغة"),
            "computer": _ar("علوم الحاسوب"), "history": _ar("التاريخ"),
            "business": _ar("إدارة أعمال"), "other": _ar("محاضرة تعليمية"),
        }
        default_title = _ar("ملخص المحاضرة")
    
    lecture_type = lecture_data.get("lecture_type", "other")
    title_raw = lecture_data.get("title", "") or default_title
    type_label = type_labels.get(lecture_type, type_labels["other"])
    
    theme_hex = {
        "medicine": "#c62828", "science": "#1b5e20", "math": "#0d47a1",
        "literature": "#4a148c", "computer": "#212121", "history": "#bf360c",
        "business": "#006064", "other": "#283593",
    }.get(lecture_type, "#283593")
    theme_color = colors.HexColor(theme_hex)
    
    doc = SimpleDocTemplate(
        output_path, pagesize=A4,
        rightMargin=1.8 * cm, leftMargin=1.8 * cm,
        topMargin=2 * cm, bottomMargin=2 * cm,
    )
    
    story = []
    styles = getSampleStyleSheet()
    
    # Header style
    header_style = ParagraphStyle(
        "Header", parent=styles["Normal"],
        fontName=bold_font, fontSize=18,
        textColor=colors.white, alignment=TA_RIGHT if not is_english else TA_LEFT,
        leading=28,
    )
    
    sub_white = ParagraphStyle(
        "SubWhite", parent=styles["Normal"],
        fontName=reg_font, fontSize=10,
        textColor=colors.HexColor("#ffffffcc"),
        alignment=TA_RIGHT if not is_english else TA_LEFT,
        leading=16,
    )
    
    sec_lbl = ParagraphStyle(
        "SectionLabel", parent=styles["Normal"],
        fontName=bold_font, fontSize=13,
        textColor=theme_color, alignment=align_body,
        leading=22, spaceAfter=4,
    )
    
    body_style = ParagraphStyle(
        "Body", parent=styles["Normal"],
        fontName=reg_font, fontSize=11,
        textColor=colors.HexColor("#212121"), alignment=align_body,
        leading=22, spaceAfter=4,
    )
    
    bullet_style = ParagraphStyle(
        "Bullet", parent=styles["Normal"],
        fontName=reg_font, fontSize=11,
        textColor=colors.HexColor("#37474f"), alignment=align_body,
        leading=20, spaceAfter=2,
        leftIndent=0 if not is_english else 8,
        rightIndent=8 if not is_english else 0,
    )
    
    keyword_style = ParagraphStyle(
        "Keyword", parent=styles["Normal"],
        fontName=bold_font, fontSize=10,
        textColor=colors.HexColor("#1565c0"), alignment=align_body,
        leading=18, spaceAfter=2,
    )
    
    footer_style = ParagraphStyle(
        "Footer", parent=styles["Normal"],
        fontName=reg_font, fontSize=9,
        textColor=colors.HexColor("#9e9e9e"), alignment=TA_CENTER,
        leading=14,
    )
    
    # Header
    title_display = fmt(title_raw) if not is_english else _clean(title_raw)
    header_table = Table(
        [[Paragraph(title_display, header_style)],
         [Paragraph(type_label, sub_white)]],
        colWidths=[17.4 * cm],
    )
    h_align = "RIGHT" if not is_english else "LEFT"
    header_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), theme_color),
        ("ALIGN", (0, 0), (-1, -1), h_align),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 14),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 14),
        ("LEFTPADDING", (0, 0), (-1, -1), 16),
        ("RIGHTPADDING", (0, 0), (-1, -1), 16),
    ]))
    story.append(header_table)
    story.append(Spacer(1, 0.5 * cm))
    
    # Summary
    summary = lecture_data.get("summary", "")
    if summary:
        story.append(Paragraph(labels["summary"], sec_lbl))
        story.append(HRFlowable(width="100%", thickness=1.5, color=theme_color))
        story.append(Spacer(1, 0.15 * cm))
        s_text = summary if is_english else fmt(summary)
        story.append(Paragraph(s_text, body_style))
        story.append(Spacer(1, 0.4 * cm))
    
    # Key points
    key_points = lecture_data.get("key_points", [])
    if key_points:
        story.append(Paragraph(labels["key_points"], sec_lbl))
        story.append(HRFlowable(width="100%", thickness=1.5, color=theme_color))
        story.append(Spacer(1, 0.15 * cm))
        for point in key_points:
            bullet = f"- {_clean(point)}" if is_english else fmt(f"- {point}")
            story.append(Paragraph(bullet, bullet_style))
        story.append(Spacer(1, 0.5 * cm))
    
    # Sections
    story.append(Paragraph(labels["sections_head"], sec_lbl))
    story.append(HRFlowable(width="100%", thickness=2, color=theme_color))
    story.append(Spacer(1, 0.3 * cm))
    
    temp_image_paths = []
    
    for i, section in enumerate(sections):
        num = i + 1
        sec_title_raw = section.get("title", f"Section {num}" if is_english else f"القسم {num}")
        
        sec_h_style = ParagraphStyle(
            f"SecH{i}", parent=styles["Normal"],
            fontSize=12, fontName=bold_font,
            textColor=colors.white,
            alignment=TA_RIGHT if not is_english else TA_LEFT,
            leading=20,
        )
        
        sec_title_txt = (f"{num}.  {_clean(sec_title_raw)}" if is_english else fmt(f"{num}.  {sec_title_raw}"))
        sec_header = Table(
            [[Paragraph(sec_title_txt, sec_h_style)]],
            colWidths=[17.4 * cm],
        )
        sec_header.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), theme_color),
            ("ALIGN", (0, 0), (-1, -1), "RIGHT" if not is_english else "LEFT"),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("TOPPADDING", (0, 0), (-1, -1), 8),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
            ("LEFTPADDING", (0, 0), (-1, -1), 12),
            ("RIGHTPADDING", (0, 0), (-1, -1), 12),
        ]))
        
        section_items = [sec_header, Spacer(1, 0.2 * cm)]
        
        # Section image
        img_bytes = section.get("_image_bytes")
        if img_bytes:
            try:
                pil_img = PILImage.open(io.BytesIO(img_bytes)).convert("RGB")
                pil_img.thumbnail((960, 540), PILImage.LANCZOS)
                img_path = os.path.join(TEMP_DIR, f"pdf_img_{i}_{uuid.uuid4().hex[:6]}.jpg")
                pil_img.save(img_path, "JPEG", quality=80)
                temp_image_paths.append(img_path)
                rl_img = Image(img_path, width=13 * cm, height=7.3 * cm)
                rl_img.hAlign = "CENTER"
                section_items.append(rl_img)
                section_items.append(Spacer(1, 0.2 * cm))
            except Exception as e:
                print(f"PDF image error section {i}: {e}")
        
        # Content
        content = section.get("content", section.get("narration", ""))
        if content:
            c_text = _clean(content) if is_english else fmt(content)
            section_items.append(Paragraph(c_text, body_style))
            section_items.append(Spacer(1, 0.15 * cm))
        
        # Keywords
        keywords = section.get("keywords", [])
        if keywords:
            kw_clean = [_clean(k) for k in keywords]
            kw_text = "  |  ".join(kw_clean)
            lbl = labels["keywords_lbl"]
            kw_full = f"{lbl} {kw_text}" if is_english else fmt(f"{lbl} {kw_text}")
            section_items.append(Paragraph(kw_full, keyword_style))
        
        section_items.append(Spacer(1, 0.3 * cm))
        section_items.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#bdbdbd")))
        section_items.append(Spacer(1, 0.3 * cm))
        
        story.append(KeepTogether(section_items[:3]))
        for item in section_items[3:]:
            story.append(item)
    
    # Footer
    story.append(Spacer(1, 0.5 * cm))
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#e0e0e0")))
    story.append(Spacer(1, 0.2 * cm))
    story.append(Paragraph(labels["footer"], footer_style))
    
    doc.build(story)
    
    # Cleanup temp images
    for img_path in temp_image_paths:
        try:
            if os.path.exists(img_path):
                os.remove(img_path)
        except Exception:
            pass
    
    return output_path
